spring:
  datasource:
    url: jdbc:h2:mem:commandesdb
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

mes-config-ms:
  commandes-last: 10

server:
  port: 8080
